import type { FreshnessLevel } from "../../shared/types/hpc";
import type { ReactNode } from "react";
import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export type Language = "en" | "de" | "hu";
type Theme = "light" | "dark";

const english = {
  navPrimary: "Primary",
  navDashboard: "Dashboard",
  navNodes: "Nodes",
  navJobs: "My Jobs",
  navHistory: "My History",
  signIn: "Sign in",
  signOut: "Sign out",
  darkMode: "Dark mode",
  lightMode: "Light mode",
  language: "Language",
  checkingSession: "Checking session…",
  loadingSignIn: "Loading sign-in…",
  signInTitle: "Sign in",
  signInDescription: "Sign in to access cluster status, your active jobs, and your personal history.",
  signInWithEntra: "Sign in with Microsoft Entra ID",
  loadingDashboard: "Loading dashboard…",
  failedDashboard: "Failed to load dashboard.",
  dashboard: "Dashboard",
  dashboardLede: "Live status comes from qstat. Timestamps are stored in UTC and shown here in Europe/Budapest.",
  lastUpdated: "Last updated",
  liveFeedHealthy: "Live feed healthy",
  updateDelayed: "Update delayed",
  dataIsStale: "Data is stale",
  collectorLooksBroken: "Collector looks broken",
  freshnessBanner: "{label}. Last collector update {time}.",
  freshnessThresholds: "5 / 15 / 60 minute thresholds",
  clusterUtilization: "Cluster utilization",
  usedOfTotalSlots: "{used} used / {total} total slots",
  runningJobs: "Running jobs",
  liveSchedulerCount: "Live scheduler count",
  queuedJobs: "Queued jobs",
  waitingInSchedulerQueue: "Waiting in scheduler queue",
  failedJobs: "Failed jobs",
  schedulerErrorInterpretation: "Explicit scheduler error/failure interpretation",
  jobsOnHold: "Jobs on hold",
  holdStatesOnly: "Hold states only",
  myActiveJobs: "My active jobs",
  previewFromCurrentJobs: "Preview from current jobs",
  health: "Health",
  clusterHealthSummary: "Cluster health summary",
  offlineNodes: "Offline nodes",
  freeSlots: "Free slots",
  healthRule: "Health rule",
  healthRuleText: "Healthy: scheduler reachable. Degraded: some nodes offline. Down: scheduler query failed.",
  capacity: "Capacity",
  utilizationInUse: "{percent}% of cluster slots are currently in use.",
  loadingNodes: "Loading nodes…",
  failedNodes: "Failed to load nodes.",
  nodes: "Nodes",
  liveNodeInventory: "Live node inventory",
  nodesPageLede: "Current host data comes from qhost. This page is a live snapshot of node capacity, load, memory, and swap.",
  totalNodes: "Total nodes",
  okNodes: "OK nodes",
  partialNodes: "Partial nodes",
  missingNodes: "Missing nodes",
  idleNodes: "Idle nodes",
  busyNodes: "Busy nodes",
  nodesFromQhost: "All hosts returned by qhost",
  completeQhostRows: "Rows with full qhost data",
  partialQhostRows: "Rows missing load or memory fields",
  missingQhostRows: "Rows with no usable host data",
  idleNodesDetail: "OK nodes with 0.00 load",
  busyNodesDetail: "OK nodes with load above 0",
  currentQhostView: "Current qhost view",
  hostname: "Hostname",
  nodeStatus: "Status",
  nodeArch: "Arch",
  ncpu: "NCPU",
  nsoc: "NSOC",
  ncor: "NCOR",
  nthr: "NTHR",
  load: "Load",
  loadPerCpu: "Load / CPU",
  memoryTotal: "Mem total",
  memoryUsed: "Mem used",
  swapTotal: "Swap total",
  swapUsed: "Swap used",
  noNodesData: "No node data yet.",
  myJobs: "My jobs",
  activeJobsPreview: "Active jobs preview",
  openMyJobs: "Open My Jobs",
  jobId: "Job ID",
  name: "Name",
  state: "State",
  submittedAt: "Submitted at",
  startedAt: "Started at",
  finishedAt: "Finished at",
  noActiveJobsRightNow: "You have no active jobs right now.",
  loadingJobs: "Loading jobs…",
  failedJobsPage: "Failed to load jobs.",
  myJobsTitle: "My Jobs",
  activeJobsAndHistory: "Active jobs and personal history",
  jobsPageLede: "Keep live jobs and 1-year finished-job history separate. Filters stay intentionally small: search, state, preset, pagination.",
  activeJobs: "Active jobs",
  currentSchedulerView: "Current scheduler view",
  activeJobsCount: "{count} active jobs",
  noActiveJobsOnCluster: "No active jobs on the cluster.",
  pastJobs: "Past jobs",
  personalJobHistory: "1-year personal job history",
  search: "Search",
  searchPlaceholder: "Job ID or name",
  datePreset: "Date preset",
  noJobsMatched: "No jobs matched the selected filters.",
  showingJobs: "Showing {shown} of {total} jobs",
  previous: "Previous",
  page: "Page",
  next: "Next",
  loadingHistory: "Loading history…",
  failedHistory: "Failed to load history.",
  myHistory: "My History",
  personalHistoricalTrends: "Personal historical trends",
  historyPageLede: "Short ranges use hourly rollups. Longer ranges switch to daily rollups to keep the page readable.",
  range: "Range",
  submitted: "Submitted",
  started: "Started",
  finished: "Finished",
  failed: "Failed",
  acrossPreset: "Across {preset}",
  jobsEnteringExecution: "Jobs entering execution",
  completedSuccessfully: "Completed successfully",
  explicitFailuresOnly: "Explicit failures only",
  trendChart: "Trend chart",
  finishedVsFailedJobs: "Finished vs failed jobs",
  preset: "Preset",
  barChartLabel: "Bar chart of finished and failed jobs for {preset}",
  pageNotFound: "Page not found",
  pageNotFoundLede: "Use the main navigation to return to dashboard, nodes, jobs, or history.",
  backToDashboard: "Back to dashboard",
  healthy: "healthy",
  degraded: "degraded",
  down: "down",
  queued: "queued",
  running: "running",
  hold: "hold",
  suspended: "suspended",
  error: "error",
  finishedState: "finished",
  deleted: "deleted",
  ok: "ok",
  partial: "partial",
  missing: "missing",
  all: "all",
} as const;

type TranslationKey = keyof typeof english;

const translations = {
  en: english,
  de: {
    navPrimary: "Hauptnavigation",
    navDashboard: "Dashboard",
    navNodes: "Nodes",
    navJobs: "Jobs",
    navHistory: "Verlauf",
    signIn: "Login",
    signOut: "Logout",
    darkMode: "Dunkelmodus",
    lightMode: "Hellmodus",
    language: "Sprache",
    checkingSession: "Sitzung wird geprüft…",
    loadingSignIn: "Anmeldung wird geladen…",
    signInTitle: "Anmelden",
    signInDescription: "Melden Sie sich an, um Cluster-Status, aktive Jobs und persönlichen Verlauf zu sehen.",
    signInWithEntra: "Mit Microsoft Entra ID anmelden",
    loadingDashboard: "Dashboard wird geladen…",
    failedDashboard: "Dashboard konnte nicht geladen werden.",
    dashboard: "Dashboard",
    dashboardLede: "Live-Status kommt von qstat. Zeitstempel werden in UTC gespeichert und hier in Europe/Budapest angezeigt.",
    lastUpdated: "Zuletzt aktualisiert",
    liveFeedHealthy: "Live-Daten ok",
    updateDelayed: "Update verzögert",
    dataIsStale: "Daten sind veraltet",
    collectorLooksBroken: "Collector scheint defekt zu sein",
    freshnessBanner: "{label}. Letztes Collector-Update {time}.",
    freshnessThresholds: "5 / 15 / 60 Minuten-Schwellen",
    clusterUtilization: "Clusterauslastung",
    usedOfTotalSlots: "{used} genutzt / {total} Slots gesamt",
    runningJobs: "Laufende Jobs",
    liveSchedulerCount: "Live-Zahl aus dem Scheduler",
    queuedJobs: "Wartende Jobs",
    waitingInSchedulerQueue: "Warten in der Scheduler-Warteschlange",
    failedJobs: "Fehlgeschlagene Jobs",
    schedulerErrorInterpretation: "Explizite Scheduler-Fehlerauswertung",
    jobsOnHold: "Jobs in Wartestellung",
    holdStatesOnly: "Nur Hold-Status",
    myActiveJobs: "Meine aktiven Jobs",
    previewFromCurrentJobs: "Vorschau aus aktuellen Jobs",
    health: "Zustand",
    clusterHealthSummary: "Cluster-Zustand",
    offlineNodes: "Offline-Knoten",
    freeSlots: "Freie Slots",
    healthRule: "Zustandsregel",
    healthRuleText: "Healthy: Scheduler erreichbar. Degraded: einige Knoten offline. Down: Scheduler-Abfrage fehlgeschlagen.",
    capacity: "Kapazität",
    utilizationInUse: "{percent}% der Cluster-Slots werden gerade genutzt.",
    loadingNodes: "Nodes werden geladen…",
    failedNodes: "Nodes konnten nicht geladen werden.",
    nodes: "Nodes",
    liveNodeInventory: "Live-Node-Inventar",
    nodesPageLede: "Aktuelle Host-Daten kommen von qhost. Diese Seite ist ein Live-Schnappschuss von Node-Kapazität, Load, Speicher und Swap.",
    totalNodes: "Nodes gesamt",
    okNodes: "OK-Nodes",
    partialNodes: "Teilweise Nodes",
    missingNodes: "Fehlende Nodes",
    idleNodes: "Idle-Nodes",
    busyNodes: "Busy-Nodes",
    nodesFromQhost: "Alle von qhost gelieferten Hosts",
    completeQhostRows: "Zeilen mit vollständigen qhost-Daten",
    partialQhostRows: "Zeilen mit fehlenden Load- oder Speicherfeldern",
    missingQhostRows: "Zeilen ohne brauchbare Host-Daten",
    idleNodesDetail: "OK-Nodes mit 0.00 Load",
    busyNodesDetail: "OK-Nodes mit Load über 0",
    currentQhostView: "Aktuelle qhost-Sicht",
    hostname: "Hostname",
    nodeStatus: "Status",
    nodeArch: "Arch",
    ncpu: "NCPU",
    nsoc: "NSOC",
    ncor: "NCOR",
    nthr: "NTHR",
    load: "Load",
    loadPerCpu: "Load / CPU",
    memoryTotal: "Mem gesamt",
    memoryUsed: "Mem genutzt",
    swapTotal: "Swap gesamt",
    swapUsed: "Swap genutzt",
    noNodesData: "Noch keine Node-Daten.",
    myJobs: "Meine Jobs",
    activeJobsPreview: "Vorschau aktiver Jobs",
    openMyJobs: "Meine Jobs öffnen",
    jobId: "Job-ID",
    name: "Name",
    state: "Status",
    submittedAt: "Eingereicht am",
    startedAt: "Gestartet am",
    finishedAt: "Beendet am",
    noActiveJobsRightNow: "Sie haben gerade keine aktiven Jobs.",
    loadingJobs: "Jobs werden geladen…",
    failedJobsPage: "Jobs konnten nicht geladen werden.",
    myJobsTitle: "Meine Jobs",
    activeJobsAndHistory: "Aktive Jobs und persönlicher Verlauf",
    jobsPageLede: "Live-Jobs und 1-Jahres-Verlauf bleiben getrennt. Filter bleiben absichtlich klein: Suche, Status, Zeitraum, Seiten.",
    activeJobs: "Aktive Jobs",
    currentSchedulerView: "Aktuelle Scheduler-Sicht",
    activeJobsCount: "{count} aktive Jobs",
    noActiveJobsOnCluster: "Keine aktiven Jobs im Cluster.",
    pastJobs: "Vergangene Jobs",
    personalJobHistory: "Persönlicher Job-Verlauf für 1 Jahr",
    search: "Suche",
    searchPlaceholder: "Job-ID oder Name",
    datePreset: "Zeitraum",
    noJobsMatched: "Keine Jobs passen zu den gewählten Filtern.",
    showingJobs: "{shown} von {total} Jobs werden angezeigt",
    previous: "Zurück",
    page: "Seite",
    next: "Weiter",
    loadingHistory: "Verlauf wird geladen…",
    failedHistory: "Verlauf konnte nicht geladen werden.",
    myHistory: "Mein Verlauf",
    personalHistoricalTrends: "Persönliche historische Trends",
    historyPageLede: "Kurze Zeiträume nutzen stündliche Rollups. Längere Zeiträume wechseln zu täglichen Rollups, damit die Seite lesbar bleibt.",
    range: "Zeitraum",
    submitted: "Eingereicht",
    started: "Gestartet",
    finished: "Beendet",
    failed: "Fehlgeschlagen",
    acrossPreset: "Über {preset}",
    jobsEnteringExecution: "Jobs starten die Ausführung",
    completedSuccessfully: "Erfolgreich abgeschlossen",
    explicitFailuresOnly: "Nur explizite Fehler",
    trendChart: "Trenddiagramm",
    finishedVsFailedJobs: "Beendete vs. fehlgeschlagene Jobs",
    preset: "Zeitraum",
    barChartLabel: "Balkendiagramm für beendete und fehlgeschlagene Jobs für {preset}",
    pageNotFound: "Seite nicht gefunden",
    pageNotFoundLede: "Verwenden Sie die Hauptnavigation, um zum Dashboard, zu Nodes, zu Jobs oder zum Verlauf zurückzukehren.",
    backToDashboard: "Zurück zum Dashboard",
    healthy: "healthy",
    degraded: "degraded",
    down: "down",
    queued: "wartend",
    running: "laufend",
    hold: "hold",
    suspended: "pausiert",
    error: "fehler",
    finishedState: "beendet",
    deleted: "gelöscht",
    ok: "ok",
    partial: "teilweise",
    missing: "fehlt",
    all: "alle",
  },
  hu: {
    navPrimary: "Elsődleges navigáció",
    navDashboard: "Vezérlőpult",
    navNodes: "Node-ok",
    navJobs: "Munkák",
    navHistory: "Előzmény",
    signIn: "Belépés",
    signOut: "Kilépés",
    darkMode: "Sötét mód",
    lightMode: "Világos mód",
    language: "Nyelv",
    checkingSession: "Munkamenet ellenőrzése…",
    loadingSignIn: "Bejelentkezés betöltése…",
    signInTitle: "Bejelentkezés",
    signInDescription: "Jelentkezzen be a klaszter állapotának, az aktív feladatoknak és a személyes előzményeknek a megtekintéséhez.",
    signInWithEntra: "Bejelentkezés Microsoft Entra ID-val",
    loadingDashboard: "Vezérlőpult betöltése…",
    failedDashboard: "A vezérlőpult nem tölthető be.",
    dashboard: "Vezérlőpult",
    dashboardLede: "Az élő állapot a qstatból jön. Az időbélyegek UTC-ben vannak tárolva, itt Europe/Budapest szerint jelennek meg.",
    lastUpdated: "Utolsó frissítés",
    liveFeedHealthy: "Az élő adatfolyam rendben van",
    updateDelayed: "A frissítés késik",
    dataIsStale: "Az adatok elavultak",
    collectorLooksBroken: "A gyűjtő hibásnak tűnik",
    freshnessBanner: "{label}. Az utolsó gyűjtőfrissítés: {time}.",
    freshnessThresholds: "5 / 15 / 60 perces küszöbök",
    clusterUtilization: "Klaszter kihasználtság",
    usedOfTotalSlots: "{used} használt / {total} összes slot",
    runningJobs: "Futó feladatok",
    liveSchedulerCount: "Élő scheduler darabszám",
    queuedJobs: "Várakozó feladatok",
    waitingInSchedulerQueue: "Várakozás a scheduler sorában",
    failedJobs: "Sikertelen feladatok",
    schedulerErrorInterpretation: "Kifejezett scheduler hibaértelmezés",
    jobsOnHold: "Tartott feladatok",
    holdStatesOnly: "Csak hold állapotok",
    myActiveJobs: "Aktív feladataim",
    previewFromCurrentJobs: "Előnézet az aktuális feladatokból",
    health: "Állapot",
    clusterHealthSummary: "Klaszter állapotösszefoglaló",
    offlineNodes: "Offline csomópontok",
    freeSlots: "Szabad slotok",
    healthRule: "Állapotszabály",
    healthRuleText: "Healthy: a scheduler elérhető. Degraded: néhány csomópont offline. Down: a scheduler lekérdezése sikertelen.",
    capacity: "Kapacitás",
    utilizationInUse: "A klaszter slotjainak {percent}%-a használatban van.",
    loadingNodes: "Node-ok betöltése…",
    failedNodes: "A node adatok nem tölthetők be.",
    nodes: "Node-ok",
    liveNodeInventory: "Élő node lista",
    nodesPageLede: "Az aktuális host adatok a qhostból jönnek. Ez az oldal a node kapacitás, load és memória élő pillanatképe.",
    totalNodes: "Összes node",
    okNodes: "OK node-ok",
    partialNodes: "Hiányos node-ok",
    missingNodes: "Hiányzó node-ok",
    idleNodes: "Üresjáratú node-ok",
    busyNodes: "Terhelt node-ok",
    nodesFromQhost: "A qhost által visszaadott összes host",
    completeQhostRows: "Teljes qhost adattal rendelkező sorok",
    partialQhostRows: "Hiányzó load vagy memória mezős sorok",
    missingQhostRows: "Használható host adat nélküli sorok",
    idleNodesDetail: "OK node-ok 0.00 load-dal",
    busyNodesDetail: "OK node-ok 0 feletti load-dal",
    currentQhostView: "Jelenlegi qhost nézet",
    hostname: "Hostname",
    nodeStatus: "Állapot",
    nodeArch: "Arch",
    ncpu: "NCPU",
    nsoc: "NSOC",
    ncor: "NCOR",
    nthr: "NTHR",
    load: "Load",
    loadPerCpu: "Load / CPU",
    memoryTotal: "Mem össz.",
    memoryUsed: "Mem haszn.",
    swapTotal: "Swap össz.",
    swapUsed: "Swap haszn.",
    noNodesData: "Még nincs node adat.",
    myJobs: "Feladataim",
    activeJobsPreview: "Aktív feladatok előnézete",
    openMyJobs: "Feladataim megnyitása",
    jobId: "Feladatazonosító",
    name: "Név",
    state: "Állapot",
    submittedAt: "Beküldve",
    startedAt: "Indítva",
    finishedAt: "Befejezve",
    noActiveJobsRightNow: "Jelenleg nincs aktív feladata.",
    loadingJobs: "Feladatok betöltése…",
    failedJobsPage: "A feladatok nem tölthetők be.",
    myJobsTitle: "Feladataim",
    activeJobsAndHistory: "Aktív feladatok és személyes előzmények",
    jobsPageLede: "Az élő feladatok és az 1 éves előzmények külön maradnak. A szűrők szándékosan egyszerűek: keresés, állapot, időtartam, lapozás.",
    activeJobs: "Aktív feladatok",
    currentSchedulerView: "Jelenlegi scheduler nézet",
    activeJobsCount: "{count} aktív feladat",
    noActiveJobsOnCluster: "Nincs aktív feladat a klaszteren.",
    pastJobs: "Korábbi feladatok",
    personalJobHistory: "1 éves személyes feladatelőzmény",
    search: "Keresés",
    searchPlaceholder: "Feladatazonosító vagy név",
    datePreset: "Időtartam",
    noJobsMatched: "Nincs találat a kiválasztott szűrőkre.",
    showingJobs: "{shown} / {total} feladat látható",
    previous: "Előző",
    page: "Oldal",
    next: "Következő",
    loadingHistory: "Előzmények betöltése…",
    failedHistory: "Az előzmények nem tölthetők be.",
    myHistory: "Előzményeim",
    personalHistoricalTrends: "Személyes történeti trendek",
    historyPageLede: "A rövid időtartamok órás összesítést használnak. A hosszabbak napi összesítésre váltanak, hogy az oldal olvasható maradjon.",
    range: "Tartomány",
    submitted: "Beküldött",
    started: "Elindult",
    finished: "Befejezett",
    failed: "Sikertelen",
    acrossPreset: "{preset} alatt",
    jobsEnteringExecution: "Végrehajtásba lépő feladatok",
    completedSuccessfully: "Sikeresen befejezve",
    explicitFailuresOnly: "Csak kifejezett hibák",
    trendChart: "Trenddiagram",
    finishedVsFailedJobs: "Befejezett vs sikertelen feladatok",
    preset: "Időtartam",
    barChartLabel: "Befejezett és sikertelen feladatok oszlopdiagramja erre: {preset}",
    pageNotFound: "Az oldal nem található",
    pageNotFoundLede: "A fő navigációval térjen vissza a vezérlőpulthoz, a node-okhoz, a feladatokhoz vagy az előzményekhez.",
    backToDashboard: "Vissza a vezérlőpultra",
    healthy: "healthy",
    degraded: "degraded",
    down: "down",
    queued: "sorban",
    running: "fut",
    hold: "hold",
    suspended: "felfüggesztve",
    error: "hiba",
    finishedState: "befejezve",
    deleted: "törölve",
    ok: "ok",
    partial: "hiányos",
    missing: "hiányzik",
    all: "összes",
  },
} satisfies Record<Language, Record<TranslationKey, string>>;

const statusKeys = {
  healthy: "healthy",
  degraded: "degraded",
  down: "down",
  queued: "queued",
  running: "running",
  hold: "hold",
  suspended: "suspended",
  error: "error",
  finished: "finishedState",
  deleted: "deleted",
  ok: "ok",
  partial: "partial",
  missing: "missing",
  all: "all",
} as const satisfies Record<string, TranslationKey>;

const freshnessKeys = {
  fresh: "liveFeedHealthy",
  warn: "updateDelayed",
  stale: "dataIsStale",
  broken: "collectorLooksBroken",
} as const satisfies Record<FreshnessLevel, TranslationKey>;

export const languageOptions = [
  { value: "en", label: "English" },
  { value: "de", label: "Deutsch" },
  { value: "hu", label: "Magyar" },
] as const;

function fill(template: string, values?: Record<string, string | number>) {
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? `{${key}}`));
}

function readStored<T extends string>(key: string, fallback: T) {
  if (typeof window === "undefined") return fallback;
  const value = window.localStorage.getItem(key);
  return value ? value as T : fallback;
}

interface UiContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  theme: Theme;
  toggleTheme: () => void;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
  statusLabel: (value: string) => string;
  freshnessLabel: (level: FreshnessLevel) => string;
}

const UiContext = createContext<UiContextValue | null>(null);

export function UiProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const language = readStored("language", "en");
    return languageOptions.some((option) => option.value === language) ? language as Language : "en";
  });
  const [theme, setTheme] = useState<Theme>(() => readStored("theme", "light"));

  useEffect(() => {
    window.localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    window.localStorage.setItem("theme", theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const value = useMemo<UiContextValue>(() => {
    const table = translations[language];
    return {
      language,
      setLanguage,
      theme,
      toggleTheme: () => setTheme((value) => value === "dark" ? "light" : "dark"),
      t: (key, values) => fill(table[key], values),
      statusLabel: (value) => {
        const key = statusKeys[value as keyof typeof statusKeys];
        return key ? table[key] : value;
      },
      freshnessLabel: (level) => table[freshnessKeys[level]],
    };
  }, [language, theme]);

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
}

export function useUi() {
  const value = useContext(UiContext);
  if (!value) throw new Error("UiProvider missing");
  return value;
}
