import type { FreshnessLevel } from "../../shared/types/hpc";
import type { ReactNode } from "react";
import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export type Language = "en" | "de" | "hu";

const english = {
  navPrimary: "Primary",
  navDashboard: "Dashboard",
  navNodes: "Nodes",
  navJobs: "My Jobs",
  navHistory: "My History",
  signOut: "Sign out",
  language: "Language",
  loadingSignIn: "Loading sign-in…",
  signInTitle: "Sign in",
  signInDescription: "Sign in to access cluster status, your active jobs, and your personal history.",
  signInWithEntra: "Sign in with Microsoft Entra ID",
  loadingDashboard: "Loading dashboard…",
  failedDashboard: "Failed to load dashboard.",
  dashboard: "Dashboard",
  dashboardLede: "Live cluster capacity, scheduler activity, and your current workload in one operational view.",
  skipToContent: "Skip to main content",
  lastUpdated: "Last updated",
  liveFeedHealthy: "Live feed healthy",
  updateDelayed: "Update delayed",
  dataIsStale: "Data is stale",
  collectorLooksBroken: "Collector looks broken",
  freshnessBanner: "{label}. Last collector update {time}.",
  clusterUtilization: "Cluster utilization",
  usedOfTotalSlots: "{used} used / {total} total slots",
  runningJobs: "Running jobs",
  queuedJobs: "Queued jobs",
  failedJobs: "Failed jobs",
  jobsOnHold: "Jobs on hold",
  clusterActivity: "Cluster activity",
  last24Hours: "Last 24 hours",
  hpcUtilizationOverTime: "HPC utilization",
  jobCountOverTime: "Active job count",
  latestValue: "Latest:",
  noClusterHistory: "Chart data will appear as new collector snapshots arrive.",
  utilizationTimeChartLabel: "HPC utilization over the last 24 hours",
  jobCountTimeChartLabel: "Active job count over the last 24 hours",
  chartInteractionHint: "Hover over the chart or use Left and Right arrow keys to inspect values.",
  loadingNodes: "Loading nodes…",
  failedNodes: "Failed to load nodes.",
  nodes: "Nodes",
  liveNodeInventory: "Live node inventory",
  nodesPageLede: "Inspect current node availability, processor load, and memory use.",
  totalNodes: "Total nodes",
  okNodes: "OK nodes",
  partialNodes: "Partial nodes",
  missingNodes: "Missing nodes",
  idleNodes: "Idle nodes",
  busyNodes: "Busy nodes",
  nodesFromQhost: "All hosts returned by qhost",
  completeQhostRows: "Rows with full qhost data",
  partialQhostRows: "Rows missing load or memory fields",
  missingQhostRows: "Rows with no usable host data",
  idleNodesDetail: "OK nodes with 0.00 load",
  busyNodesDetail: "OK nodes with load above 0",
  currentQhostView: "Current qhost view",
  hostname: "Hostname",
  nodeStatus: "Status",
  nodeArch: "Arch",
  ncpu: "NCPU",
  nsoc: "NSOC",
  ncor: "NCOR",
  nthr: "NTHR",
  load: "Load",
  loadPerCpu: "Load / CPU",
  memoryTotal: "Mem total",
  memoryUsed: "Mem used",
  noNodesData: "No node data yet.",
  myJobs: "My jobs",
  openMyJobs: "Open My Jobs",
  jobId: "Job ID",
  name: "Name",
  state: "State",
  submittedAt: "Submitted at",
  startedAt: "Started at",
  finishedAt: "Finished at",
  noActiveJobsRightNow: "You have no active jobs right now.",
  loadingJobs: "Loading jobs…",
  failedJobsPage: "Failed to load jobs.",
  activeJobsAndHistory: "Active jobs and personal history",
  jobsPageLede: "Monitor active work and search your job history from the past year.",
  activeJobs: "Active jobs",
  currentSchedulerView: "Current scheduler view",
  activeJobsCount: "{count} active jobs",
  noActiveJobsOnCluster: "No active jobs on the cluster.",
  personalJobHistory: "1-year personal job history",
  search: "Search",
  searchPlaceholder: "Job ID or name",
  datePreset: "Date preset",
  noJobsMatched: "No jobs matched the selected filters.",
  showingJobs: "Showing {shown} of {total} jobs",
  previous: "Previous",
  page: "Page",
  next: "Next",
  loadingHistory: "Loading history…",
  failedHistory: "Failed to load history.",
  personalHistoricalTrends: "Personal historical trends",
  historyPageLede: "Compare submitted, started, completed, and failed jobs across the selected period.",
  range: "Range",
  submitted: "Submitted",
  started: "Started",
  finished: "Finished",
  failed: "Failed",
  acrossPreset: "Across {preset}",
  jobsEnteringExecution: "Jobs entering execution",
  completedSuccessfully: "Completed successfully",
  explicitFailuresOnly: "Explicit failures only",
  finishedVsFailedJobs: "Finished vs failed jobs",
  barChartLabel: "Bar chart of finished and failed jobs for {preset}",
  noHistoryChartData: "No historical chart data is available for this range.",
  pageNotFound: "Page not found",
  pageNotFoundLede: "Use the main navigation to return to dashboard, nodes, jobs, or history.",
  backToDashboard: "Back to dashboard",
  healthy: "healthy",
  degraded: "degraded",
  down: "down",
  queued: "queued",
  running: "running",
  hold: "hold",
  suspended: "suspended",
  error: "error",
  finishedState: "finished",
  deleted: "deleted",
  ok: "ok",
  partial: "partial",
  missing: "missing",
  all: "all",
} as const;

type TranslationKey = keyof typeof english;

const translations = {
  en: english,
  de: {
    navPrimary: "Hauptnavigation",
    navDashboard: "Dashboard",
    navNodes: "Nodes",
    navJobs: "Jobs",
    navHistory: "Verlauf",
    signOut: "Logout",
    language: "Sprache",
    loadingSignIn: "Anmeldung wird geladen…",
    signInTitle: "Anmelden",
    signInDescription: "Melden Sie sich an, um Cluster-Status, aktive Jobs und persönlichen Verlauf zu sehen.",
    signInWithEntra: "Mit Microsoft Entra ID anmelden",
    loadingDashboard: "Dashboard wird geladen…",
    failedDashboard: "Dashboard konnte nicht geladen werden.",
    dashboard: "Dashboard",
    dashboardLede: "Live-Clusterkapazität, Scheduler-Aktivität und Ihre aktuelle Auslastung in einer operativen Ansicht.",
    skipToContent: "Zum Hauptinhalt springen",
    lastUpdated: "Zuletzt aktualisiert",
    liveFeedHealthy: "Live-Daten ok",
    updateDelayed: "Update verzögert",
    dataIsStale: "Daten sind veraltet",
    collectorLooksBroken: "Collector scheint defekt zu sein",
    freshnessBanner: "{label}. Letztes Collector-Update {time}.",
    clusterUtilization: "Clusterauslastung",
    usedOfTotalSlots: "{used} genutzt / {total} Slots gesamt",
    runningJobs: "Laufende Jobs",
    queuedJobs: "Wartende Jobs",
    failedJobs: "Fehlgeschlagene Jobs",
    jobsOnHold: "Jobs in Wartestellung",
    clusterActivity: "Clusteraktivität",
    last24Hours: "Letzte 24 Stunden",
    hpcUtilizationOverTime: "HPC-Auslastung",
    jobCountOverTime: "Anzahl aktiver Jobs",
    latestValue: "Aktuell:",
    noClusterHistory: "Diagrammdaten erscheinen, sobald neue Collector-Snapshots eintreffen.",
    utilizationTimeChartLabel: "HPC-Auslastung in den letzten 24 Stunden",
    jobCountTimeChartLabel: "Anzahl aktiver Jobs in den letzten 24 Stunden",
    chartInteractionHint: "Bewegen Sie den Zeiger über das Diagramm oder prüfen Sie Werte mit der linken und rechten Pfeiltaste.",
    loadingNodes: "Nodes werden geladen…",
    failedNodes: "Nodes konnten nicht geladen werden.",
    nodes: "Nodes",
    liveNodeInventory: "Live-Node-Inventar",
    nodesPageLede: "Prüfen Sie die aktuelle Node-Verfügbarkeit, Prozessorauslastung und Speichernutzung.",
    totalNodes: "Nodes gesamt",
    okNodes: "OK-Nodes",
    partialNodes: "Teilweise Nodes",
    missingNodes: "Fehlende Nodes",
    idleNodes: "Idle-Nodes",
    busyNodes: "Busy-Nodes",
    nodesFromQhost: "Alle von qhost gelieferten Hosts",
    completeQhostRows: "Zeilen mit vollständigen qhost-Daten",
    partialQhostRows: "Zeilen mit fehlenden Load- oder Speicherfeldern",
    missingQhostRows: "Zeilen ohne brauchbare Host-Daten",
    idleNodesDetail: "OK-Nodes mit 0.00 Load",
    busyNodesDetail: "OK-Nodes mit Load über 0",
    currentQhostView: "Aktuelle qhost-Sicht",
    hostname: "Hostname",
    nodeStatus: "Status",
    nodeArch: "Arch",
    ncpu: "NCPU",
    nsoc: "NSOC",
    ncor: "NCOR",
    nthr: "NTHR",
    load: "Load",
    loadPerCpu: "Load / CPU",
    memoryTotal: "Mem gesamt",
    memoryUsed: "Mem genutzt",
    noNodesData: "Noch keine Node-Daten.",
    myJobs: "Meine Jobs",
    openMyJobs: "Meine Jobs öffnen",
    jobId: "Job-ID",
    name: "Name",
    state: "Status",
    submittedAt: "Eingereicht am",
    startedAt: "Gestartet am",
    finishedAt: "Beendet am",
    noActiveJobsRightNow: "Sie haben gerade keine aktiven Jobs.",
    loadingJobs: "Jobs werden geladen…",
    failedJobsPage: "Jobs konnten nicht geladen werden.",
    activeJobsAndHistory: "Aktive Jobs und persönlicher Verlauf",
    jobsPageLede: "Überwachen Sie aktive Jobs und durchsuchen Sie Ihren Job-Verlauf des letzten Jahres.",
    activeJobs: "Aktive Jobs",
    currentSchedulerView: "Aktuelle Scheduler-Sicht",
    activeJobsCount: "{count} aktive Jobs",
    noActiveJobsOnCluster: "Keine aktiven Jobs im Cluster.",
    personalJobHistory: "Persönlicher Job-Verlauf für 1 Jahr",
    search: "Suche",
    searchPlaceholder: "Job-ID oder Name",
    datePreset: "Zeitraum",
    noJobsMatched: "Keine Jobs passen zu den gewählten Filtern.",
    showingJobs: "{shown} von {total} Jobs werden angezeigt",
    previous: "Zurück",
    page: "Seite",
    next: "Weiter",
    loadingHistory: "Verlauf wird geladen…",
    failedHistory: "Verlauf konnte nicht geladen werden.",
    personalHistoricalTrends: "Persönliche historische Trends",
    historyPageLede: "Vergleichen Sie eingereichte, gestartete, beendete und fehlgeschlagene Jobs im gewählten Zeitraum.",
    range: "Zeitraum",
    submitted: "Eingereicht",
    started: "Gestartet",
    finished: "Beendet",
    failed: "Fehlgeschlagen",
    acrossPreset: "Über {preset}",
    jobsEnteringExecution: "Jobs starten die Ausführung",
    completedSuccessfully: "Erfolgreich abgeschlossen",
    explicitFailuresOnly: "Nur explizite Fehler",
    finishedVsFailedJobs: "Beendete vs. fehlgeschlagene Jobs",
    barChartLabel: "Balkendiagramm für beendete und fehlgeschlagene Jobs für {preset}",
    noHistoryChartData: "Für diesen Zeitraum sind keine historischen Diagrammdaten verfügbar.",
    pageNotFound: "Seite nicht gefunden",
    pageNotFoundLede: "Verwenden Sie die Hauptnavigation, um zum Dashboard, zu Nodes, zu Jobs oder zum Verlauf zurückzukehren.",
    backToDashboard: "Zurück zum Dashboard",
    healthy: "healthy",
    degraded: "degraded",
    down: "down",
    queued: "wartend",
    running: "laufend",
    hold: "hold",
    suspended: "pausiert",
    error: "fehler",
    finishedState: "beendet",
    deleted: "gelöscht",
    ok: "ok",
    partial: "teilweise",
    missing: "fehlt",
    all: "alle",
  },
  hu: {
    navPrimary: "Elsődleges navigáció",
    navDashboard: "Vezérlőpult",
    navNodes: "Node-ok",
    navJobs: "Munkák",
    navHistory: "Előzmény",
    signOut: "Kilépés",
    language: "Nyelv",
    loadingSignIn: "Bejelentkezés betöltése…",
    signInTitle: "Bejelentkezés",
    signInDescription: "Jelentkezzen be a klaszter állapotának, az aktív feladatoknak és a személyes előzményeknek a megtekintéséhez.",
    signInWithEntra: "Bejelentkezés Microsoft Entra ID-val",
    loadingDashboard: "Vezérlőpult betöltése…",
    failedDashboard: "A vezérlőpult nem tölthető be.",
    dashboard: "Vezérlőpult",
    dashboardLede: "Élő klaszterkapacitás, scheduler-aktivitás és az aktuális terhelés egyetlen operatív nézetben.",
    skipToContent: "Ugrás a fő tartalomhoz",
    lastUpdated: "Utolsó frissítés",
    liveFeedHealthy: "Az élő adatfolyam rendben van",
    updateDelayed: "A frissítés késik",
    dataIsStale: "Az adatok elavultak",
    collectorLooksBroken: "A gyűjtő hibásnak tűnik",
    freshnessBanner: "{label}. Az utolsó gyűjtőfrissítés: {time}.",
    clusterUtilization: "Klaszter kihasználtság",
    usedOfTotalSlots: "{used} használt / {total} összes slot",
    runningJobs: "Futó feladatok",
    queuedJobs: "Várakozó feladatok",
    failedJobs: "Sikertelen feladatok",
    jobsOnHold: "Tartott feladatok",
    clusterActivity: "Klaszteraktivitás",
    last24Hours: "Utolsó 24 óra",
    hpcUtilizationOverTime: "HPC-kihasználtság",
    jobCountOverTime: "Aktív feladatok száma",
    latestValue: "Legutóbbi:",
    noClusterHistory: "A diagram adatai az új gyűjtőpillanatképekkel jelennek meg.",
    utilizationTimeChartLabel: "HPC-kihasználtság az utolsó 24 órában",
    jobCountTimeChartLabel: "Aktív feladatok száma az utolsó 24 órában",
    chartInteractionHint: "Mutasson a diagramra, vagy a bal és jobb nyílbillentyűvel vizsgálja meg az értékeket.",
    loadingNodes: "Node-ok betöltése…",
    failedNodes: "A node adatok nem tölthetők be.",
    nodes: "Node-ok",
    liveNodeInventory: "Élő node lista",
    nodesPageLede: "Tekintse át a node-ok elérhetőségét, processzorterhelését és memóriahasználatát.",
    totalNodes: "Összes node",
    okNodes: "OK node-ok",
    partialNodes: "Hiányos node-ok",
    missingNodes: "Hiányzó node-ok",
    idleNodes: "Üresjáratú node-ok",
    busyNodes: "Terhelt node-ok",
    nodesFromQhost: "A qhost által visszaadott összes host",
    completeQhostRows: "Teljes qhost adattal rendelkező sorok",
    partialQhostRows: "Hiányzó load vagy memória mezős sorok",
    missingQhostRows: "Használható host adat nélküli sorok",
    idleNodesDetail: "OK node-ok 0.00 load-dal",
    busyNodesDetail: "OK node-ok 0 feletti load-dal",
    currentQhostView: "Jelenlegi qhost nézet",
    hostname: "Hostname",
    nodeStatus: "Állapot",
    nodeArch: "Arch",
    ncpu: "NCPU",
    nsoc: "NSOC",
    ncor: "NCOR",
    nthr: "NTHR",
    load: "Load",
    loadPerCpu: "Load / CPU",
    memoryTotal: "Mem össz.",
    memoryUsed: "Mem haszn.",
    noNodesData: "Még nincs node adat.",
    myJobs: "Feladataim",
    openMyJobs: "Feladataim megnyitása",
    jobId: "Feladatazonosító",
    name: "Név",
    state: "Állapot",
    submittedAt: "Beküldve",
    startedAt: "Indítva",
    finishedAt: "Befejezve",
    noActiveJobsRightNow: "Jelenleg nincs aktív feladata.",
    loadingJobs: "Feladatok betöltése…",
    failedJobsPage: "A feladatok nem tölthetők be.",
    activeJobsAndHistory: "Aktív feladatok és személyes előzmények",
    jobsPageLede: "Kövesse az aktív feladatokat, és keressen az elmúlt év feladatelőzményeiben.",
    activeJobs: "Aktív feladatok",
    currentSchedulerView: "Jelenlegi scheduler nézet",
    activeJobsCount: "{count} aktív feladat",
    noActiveJobsOnCluster: "Nincs aktív feladat a klaszteren.",
    personalJobHistory: "1 éves személyes feladatelőzmény",
    search: "Keresés",
    searchPlaceholder: "Feladatazonosító vagy név",
    datePreset: "Időtartam",
    noJobsMatched: "Nincs találat a kiválasztott szűrőkre.",
    showingJobs: "{shown} / {total} feladat látható",
    previous: "Előző",
    page: "Oldal",
    next: "Következő",
    loadingHistory: "Előzmények betöltése…",
    failedHistory: "Az előzmények nem tölthetők be.",
    personalHistoricalTrends: "Személyes történeti trendek",
    historyPageLede: "Hasonlítsa össze a beküldött, elindult, befejezett és sikertelen feladatokat a kiválasztott időszakban.",
    range: "Tartomány",
    submitted: "Beküldött",
    started: "Elindult",
    finished: "Befejezett",
    failed: "Sikertelen",
    acrossPreset: "{preset} alatt",
    jobsEnteringExecution: "Végrehajtásba lépő feladatok",
    completedSuccessfully: "Sikeresen befejezve",
    explicitFailuresOnly: "Csak kifejezett hibák",
    finishedVsFailedJobs: "Befejezett vs sikertelen feladatok",
    barChartLabel: "Befejezett és sikertelen feladatok oszlopdiagramja erre: {preset}",
    noHistoryChartData: "Ehhez az időtartamhoz nem érhető el történeti diagramadat.",
    pageNotFound: "Az oldal nem található",
    pageNotFoundLede: "A fő navigációval térjen vissza a vezérlőpulthoz, a node-okhoz, a feladatokhoz vagy az előzményekhez.",
    backToDashboard: "Vissza a vezérlőpultra",
    healthy: "healthy",
    degraded: "degraded",
    down: "down",
    queued: "sorban",
    running: "fut",
    hold: "hold",
    suspended: "felfüggesztve",
    error: "hiba",
    finishedState: "befejezve",
    deleted: "törölve",
    ok: "ok",
    partial: "hiányos",
    missing: "hiányzik",
    all: "összes",
  },
} satisfies Record<Language, Record<TranslationKey, string>>;

const statusKeys = {
  healthy: "healthy",
  degraded: "degraded",
  down: "down",
  queued: "queued",
  running: "running",
  hold: "hold",
  suspended: "suspended",
  error: "error",
  finished: "finishedState",
  deleted: "deleted",
  ok: "ok",
  partial: "partial",
  missing: "missing",
  all: "all",
} as const satisfies Record<string, TranslationKey>;

const freshnessKeys = {
  fresh: "liveFeedHealthy",
  warn: "updateDelayed",
  stale: "dataIsStale",
  broken: "collectorLooksBroken",
} as const satisfies Record<FreshnessLevel, TranslationKey>;

export const languageOptions = [
  { value: "en", label: "English" },
  { value: "de", label: "Deutsch" },
  { value: "hu", label: "Magyar" },
] as const;

function fill(template: string, values?: Record<string, string | number>) {
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? `{${key}}`));
}

function readStored<T extends string>(key: string, fallback: T) {
  if (typeof window === "undefined") return fallback;
  const value = window.localStorage.getItem(key);
  return value ? value as T : fallback;
}

interface UiContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
  statusLabel: (value: string) => string;
  freshnessLabel: (level: FreshnessLevel) => string;
}

const UiContext = createContext<UiContextValue | null>(null);

export function UiProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const language = readStored("language", "en");
    return languageOptions.some((option) => option.value === language) ? language as Language : "en";
  });

  useEffect(() => {
    window.localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<UiContextValue>(() => {
    const table = translations[language];
    return {
      language,
      setLanguage,
      t: (key, values) => fill(table[key], values),
      statusLabel: (value) => {
        const key = statusKeys[value as keyof typeof statusKeys];
        return key ? table[key] : value;
      },
      freshnessLabel: (level) => table[freshnessKeys[level]],
    };
  }, [language]);

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
}

export function useUi() {
  const value = useContext(UiContext);
  if (!value) throw new Error("UiProvider missing");
  return value;
}
