import type { FreshnessLevel } from "../../shared/types/hpc";
import type { ReactNode } from "react";
import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export type Language = "en" | "de" | "hu" | "zh";
type Theme = "light" | "dark";

const english = {
  navPrimary: "Primary",
  navDashboard: "Dashboard",
  navJobs: "My Jobs",
  navHistory: "My History",
  signIn: "Sign in",
  signOut: "Sign out",
  darkMode: "Dark mode",
  lightMode: "Light mode",
  language: "Language",
  checkingSession: "Checking session…",
  loadingSignIn: "Loading sign-in…",
  signInTitle: "Sign in",
  signInDescription: "Sign in to access cluster status, your active jobs, and your personal history.",
  signInWithEntra: "Sign in with Microsoft Entra ID",
  loadingDashboard: "Loading dashboard…",
  failedDashboard: "Failed to load dashboard.",
  dashboard: "Dashboard",
  dashboardLede: "Live status comes from qstat. Timestamps are stored in UTC and shown here in Europe/Budapest.",
  lastUpdated: "Last updated",
  liveFeedHealthy: "Live feed healthy",
  updateDelayed: "Update delayed",
  dataIsStale: "Data is stale",
  collectorLooksBroken: "Collector looks broken",
  freshnessBanner: "{label}. Last collector update {time}.",
  freshnessThresholds: "5 / 15 / 60 minute thresholds",
  clusterUtilization: "Cluster utilization",
  usedOfTotalSlots: "{used} used / {total} total slots",
  runningJobs: "Running jobs",
  liveSchedulerCount: "Live scheduler count",
  queuedJobs: "Queued jobs",
  waitingInSchedulerQueue: "Waiting in scheduler queue",
  failedJobs: "Failed jobs",
  schedulerErrorInterpretation: "Explicit scheduler error/failure interpretation",
  jobsOnHold: "Jobs on hold",
  holdStatesOnly: "Hold states only",
  myActiveJobs: "My active jobs",
  previewFromCurrentJobs: "Preview from current jobs",
  health: "Health",
  clusterHealthSummary: "Cluster health summary",
  offlineNodes: "Offline nodes",
  freeSlots: "Free slots",
  healthRule: "Health rule",
  healthRuleText: "Healthy: scheduler reachable. Degraded: some nodes offline. Down: scheduler query failed.",
  capacity: "Capacity",
  utilizationInUse: "{percent}% of cluster slots are currently in use.",
  myJobs: "My jobs",
  activeJobsPreview: "Active jobs preview",
  openMyJobs: "Open My Jobs",
  jobId: "Job ID",
  name: "Name",
  state: "State",
  submittedAt: "Submitted at",
  startedAt: "Started at",
  finishedAt: "Finished at",
  noActiveJobsRightNow: "You have no active jobs right now.",
  loadingJobs: "Loading jobs…",
  failedJobsPage: "Failed to load jobs.",
  myJobsTitle: "My Jobs",
  activeJobsAndHistory: "Active jobs and personal history",
  jobsPageLede: "Keep live jobs and 1-year finished-job history separate. Filters stay intentionally small: search, state, preset, pagination.",
  activeJobs: "Active jobs",
  currentSchedulerView: "Current scheduler view",
  activeJobsCount: "{count} active jobs",
  noActiveJobsOnCluster: "No active jobs on the cluster.",
  pastJobs: "Past jobs",
  personalJobHistory: "1-year personal job history",
  search: "Search",
  searchPlaceholder: "Job ID or name",
  datePreset: "Date preset",
  noJobsMatched: "No jobs matched the selected filters.",
  showingJobs: "Showing {shown} of {total} jobs",
  previous: "Previous",
  page: "Page",
  next: "Next",
  loadingHistory: "Loading history…",
  failedHistory: "Failed to load history.",
  myHistory: "My History",
  personalHistoricalTrends: "Personal historical trends",
  historyPageLede: "Short ranges use hourly rollups. Longer ranges switch to daily rollups to keep the page readable.",
  range: "Range",
  submitted: "Submitted",
  started: "Started",
  finished: "Finished",
  failed: "Failed",
  acrossPreset: "Across {preset}",
  jobsEnteringExecution: "Jobs entering execution",
  completedSuccessfully: "Completed successfully",
  explicitFailuresOnly: "Explicit failures only",
  trendChart: "Trend chart",
  finishedVsFailedJobs: "Finished vs failed jobs",
  preset: "Preset",
  barChartLabel: "Bar chart of finished and failed jobs for {preset}",
  pageNotFound: "Page not found",
  pageNotFoundLede: "Use the main navigation to return to dashboard, jobs, or history.",
  backToDashboard: "Back to dashboard",
  healthy: "healthy",
  degraded: "degraded",
  down: "down",
  queued: "queued",
  running: "running",
  hold: "hold",
  suspended: "suspended",
  error: "error",
  finishedState: "finished",
  deleted: "deleted",
  all: "all",
} as const;

type TranslationKey = keyof typeof english;

const translations = {
  en: english,
  de: {
    navPrimary: "Hauptnavigation",
    navDashboard: "Dashboard",
    navJobs: "Meine Jobs",
    navHistory: "Mein Verlauf",
    signIn: "Anmelden",
    signOut: "Abmelden",
    darkMode: "Dunkelmodus",
    lightMode: "Hellmodus",
    language: "Sprache",
    checkingSession: "Sitzung wird geprüft…",
    loadingSignIn: "Anmeldung wird geladen…",
    signInTitle: "Anmelden",
    signInDescription: "Melden Sie sich an, um Cluster-Status, aktive Jobs und persönlichen Verlauf zu sehen.",
    signInWithEntra: "Mit Microsoft Entra ID anmelden",
    loadingDashboard: "Dashboard wird geladen…",
    failedDashboard: "Dashboard konnte nicht geladen werden.",
    dashboard: "Dashboard",
    dashboardLede: "Live-Status kommt von qstat. Zeitstempel werden in UTC gespeichert und hier in Europe/Budapest angezeigt.",
    lastUpdated: "Zuletzt aktualisiert",
    liveFeedHealthy: "Live-Daten ok",
    updateDelayed: "Update verzögert",
    dataIsStale: "Daten sind veraltet",
    collectorLooksBroken: "Collector scheint defekt zu sein",
    freshnessBanner: "{label}. Letztes Collector-Update {time}.",
    freshnessThresholds: "5 / 15 / 60 Minuten-Schwellen",
    clusterUtilization: "Clusterauslastung",
    usedOfTotalSlots: "{used} genutzt / {total} Slots gesamt",
    runningJobs: "Laufende Jobs",
    liveSchedulerCount: "Live-Zahl aus dem Scheduler",
    queuedJobs: "Wartende Jobs",
    waitingInSchedulerQueue: "Warten in der Scheduler-Warteschlange",
    failedJobs: "Fehlgeschlagene Jobs",
    schedulerErrorInterpretation: "Explizite Scheduler-Fehlerauswertung",
    jobsOnHold: "Jobs in Wartestellung",
    holdStatesOnly: "Nur Hold-Status",
    myActiveJobs: "Meine aktiven Jobs",
    previewFromCurrentJobs: "Vorschau aus aktuellen Jobs",
    health: "Zustand",
    clusterHealthSummary: "Cluster-Zustand",
    offlineNodes: "Offline-Knoten",
    freeSlots: "Freie Slots",
    healthRule: "Zustandsregel",
    healthRuleText: "Healthy: Scheduler erreichbar. Degraded: einige Knoten offline. Down: Scheduler-Abfrage fehlgeschlagen.",
    capacity: "Kapazität",
    utilizationInUse: "{percent}% der Cluster-Slots werden gerade genutzt.",
    myJobs: "Meine Jobs",
    activeJobsPreview: "Vorschau aktiver Jobs",
    openMyJobs: "Meine Jobs öffnen",
    jobId: "Job-ID",
    name: "Name",
    state: "Status",
    submittedAt: "Eingereicht am",
    startedAt: "Gestartet am",
    finishedAt: "Beendet am",
    noActiveJobsRightNow: "Sie haben gerade keine aktiven Jobs.",
    loadingJobs: "Jobs werden geladen…",
    failedJobsPage: "Jobs konnten nicht geladen werden.",
    myJobsTitle: "Meine Jobs",
    activeJobsAndHistory: "Aktive Jobs und persönlicher Verlauf",
    jobsPageLede: "Live-Jobs und 1-Jahres-Verlauf bleiben getrennt. Filter bleiben absichtlich klein: Suche, Status, Zeitraum, Seiten.",
    activeJobs: "Aktive Jobs",
    currentSchedulerView: "Aktuelle Scheduler-Sicht",
    activeJobsCount: "{count} aktive Jobs",
    noActiveJobsOnCluster: "Keine aktiven Jobs im Cluster.",
    pastJobs: "Vergangene Jobs",
    personalJobHistory: "Persönlicher Job-Verlauf für 1 Jahr",
    search: "Suche",
    searchPlaceholder: "Job-ID oder Name",
    datePreset: "Zeitraum",
    noJobsMatched: "Keine Jobs passen zu den gewählten Filtern.",
    showingJobs: "{shown} von {total} Jobs werden angezeigt",
    previous: "Zurück",
    page: "Seite",
    next: "Weiter",
    loadingHistory: "Verlauf wird geladen…",
    failedHistory: "Verlauf konnte nicht geladen werden.",
    myHistory: "Mein Verlauf",
    personalHistoricalTrends: "Persönliche historische Trends",
    historyPageLede: "Kurze Zeiträume nutzen stündliche Rollups. Längere Zeiträume wechseln zu täglichen Rollups, damit die Seite lesbar bleibt.",
    range: "Zeitraum",
    submitted: "Eingereicht",
    started: "Gestartet",
    finished: "Beendet",
    failed: "Fehlgeschlagen",
    acrossPreset: "Über {preset}",
    jobsEnteringExecution: "Jobs starten die Ausführung",
    completedSuccessfully: "Erfolgreich abgeschlossen",
    explicitFailuresOnly: "Nur explizite Fehler",
    trendChart: "Trenddiagramm",
    finishedVsFailedJobs: "Beendete vs. fehlgeschlagene Jobs",
    preset: "Zeitraum",
    barChartLabel: "Balkendiagramm für beendete und fehlgeschlagene Jobs für {preset}",
    pageNotFound: "Seite nicht gefunden",
    pageNotFoundLede: "Verwenden Sie die Hauptnavigation, um zum Dashboard, zu Jobs oder zum Verlauf zurückzukehren.",
    backToDashboard: "Zurück zum Dashboard",
    healthy: "healthy",
    degraded: "degraded",
    down: "down",
    queued: "wartend",
    running: "laufend",
    hold: "hold",
    suspended: "pausiert",
    error: "fehler",
    finishedState: "beendet",
    deleted: "gelöscht",
    all: "alle",
  },
  hu: {
    navPrimary: "Elsődleges navigáció",
    navDashboard: "Vezérlőpult",
    navJobs: "Feladataim",
    navHistory: "Előzményeim",
    signIn: "Bejelentkezés",
    signOut: "Kijelentkezés",
    darkMode: "Sötét mód",
    lightMode: "Világos mód",
    language: "Nyelv",
    checkingSession: "Munkamenet ellenőrzése…",
    loadingSignIn: "Bejelentkezés betöltése…",
    signInTitle: "Bejelentkezés",
    signInDescription: "Jelentkezzen be a klaszter állapotának, az aktív feladatoknak és a személyes előzményeknek a megtekintéséhez.",
    signInWithEntra: "Bejelentkezés Microsoft Entra ID-val",
    loadingDashboard: "Vezérlőpult betöltése…",
    failedDashboard: "A vezérlőpult nem tölthető be.",
    dashboard: "Vezérlőpult",
    dashboardLede: "Az élő állapot a qstatból jön. Az időbélyegek UTC-ben vannak tárolva, itt Europe/Budapest szerint jelennek meg.",
    lastUpdated: "Utolsó frissítés",
    liveFeedHealthy: "Az élő adatfolyam rendben van",
    updateDelayed: "A frissítés késik",
    dataIsStale: "Az adatok elavultak",
    collectorLooksBroken: "A gyűjtő hibásnak tűnik",
    freshnessBanner: "{label}. Az utolsó gyűjtőfrissítés: {time}.",
    freshnessThresholds: "5 / 15 / 60 perces küszöbök",
    clusterUtilization: "Klaszterkihasználtság",
    usedOfTotalSlots: "{used} használt / {total} összes slot",
    runningJobs: "Futó feladatok",
    liveSchedulerCount: "Élő scheduler darabszám",
    queuedJobs: "Várakozó feladatok",
    waitingInSchedulerQueue: "Várakozás a scheduler sorában",
    failedJobs: "Sikertelen feladatok",
    schedulerErrorInterpretation: "Kifejezett scheduler hibaértelmezés",
    jobsOnHold: "Tartott feladatok",
    holdStatesOnly: "Csak hold állapotok",
    myActiveJobs: "Aktív feladataim",
    previewFromCurrentJobs: "Előnézet az aktuális feladatokból",
    health: "Állapot",
    clusterHealthSummary: "Klaszter állapotösszefoglaló",
    offlineNodes: "Offline csomópontok",
    freeSlots: "Szabad slotok",
    healthRule: "Állapotszabály",
    healthRuleText: "Healthy: a scheduler elérhető. Degraded: néhány csomópont offline. Down: a scheduler lekérdezése sikertelen.",
    capacity: "Kapacitás",
    utilizationInUse: "A klaszter slotjainak {percent}%-a használatban van.",
    myJobs: "Feladataim",
    activeJobsPreview: "Aktív feladatok előnézete",
    openMyJobs: "Feladataim megnyitása",
    jobId: "Feladatazonosító",
    name: "Név",
    state: "Állapot",
    submittedAt: "Beküldve",
    startedAt: "Indítva",
    finishedAt: "Befejezve",
    noActiveJobsRightNow: "Jelenleg nincs aktív feladata.",
    loadingJobs: "Feladatok betöltése…",
    failedJobsPage: "A feladatok nem tölthetők be.",
    myJobsTitle: "Feladataim",
    activeJobsAndHistory: "Aktív feladatok és személyes előzmények",
    jobsPageLede: "Az élő feladatok és az 1 éves előzmények külön maradnak. A szűrők szándékosan egyszerűek: keresés, állapot, időtartam, lapozás.",
    activeJobs: "Aktív feladatok",
    currentSchedulerView: "Jelenlegi scheduler nézet",
    activeJobsCount: "{count} aktív feladat",
    noActiveJobsOnCluster: "Nincs aktív feladat a klaszteren.",
    pastJobs: "Korábbi feladatok",
    personalJobHistory: "1 éves személyes feladatelőzmény",
    search: "Keresés",
    searchPlaceholder: "Feladatazonosító vagy név",
    datePreset: "Időtartam",
    noJobsMatched: "Nincs találat a kiválasztott szűrőkre.",
    showingJobs: "{shown} / {total} feladat látható",
    previous: "Előző",
    page: "Oldal",
    next: "Következő",
    loadingHistory: "Előzmények betöltése…",
    failedHistory: "Az előzmények nem tölthetők be.",
    myHistory: "Előzményeim",
    personalHistoricalTrends: "Személyes történeti trendek",
    historyPageLede: "A rövid időtartamok órás összesítést használnak. A hosszabbak napi összesítésre váltanak, hogy az oldal olvasható maradjon.",
    range: "Tartomány",
    submitted: "Beküldött",
    started: "Elindult",
    finished: "Befejezett",
    failed: "Sikertelen",
    acrossPreset: "{preset} alatt",
    jobsEnteringExecution: "Végrehajtásba lépő feladatok",
    completedSuccessfully: "Sikeresen befejezve",
    explicitFailuresOnly: "Csak kifejezett hibák",
    trendChart: "Trenddiagram",
    finishedVsFailedJobs: "Befejezett vs sikertelen feladatok",
    preset: "Időtartam",
    barChartLabel: "Befejezett és sikertelen feladatok oszlopdiagramja erre: {preset}",
    pageNotFound: "Az oldal nem található",
    pageNotFoundLede: "A fő navigációval térjen vissza a vezérlőpulthoz, a feladatokhoz vagy az előzményekhez.",
    backToDashboard: "Vissza a vezérlőpultra",
    healthy: "healthy",
    degraded: "degraded",
    down: "down",
    queued: "sorban",
    running: "fut",
    hold: "hold",
    suspended: "felfüggesztve",
    error: "hiba",
    finishedState: "befejezve",
    deleted: "törölve",
    all: "összes",
  },
  zh: {
    navPrimary: "主导航",
    navDashboard: "仪表板",
    navJobs: "我的作业",
    navHistory: "我的历史",
    signIn: "登录",
    signOut: "退出登录",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    language: "语言",
    checkingSession: "正在检查会话…",
    loadingSignIn: "正在加载登录…",
    signInTitle: "登录",
    signInDescription: "登录后可查看集群状态、当前作业和个人历史记录。",
    signInWithEntra: "使用 Microsoft Entra ID 登录",
    loadingDashboard: "正在加载仪表板…",
    failedDashboard: "无法加载仪表板。",
    dashboard: "仪表板",
    dashboardLede: "实时状态来自 qstat。时间戳以 UTC 存储，并在这里按 Europe/Budapest 显示。",
    lastUpdated: "最后更新",
    liveFeedHealthy: "实时数据正常",
    updateDelayed: "更新延迟",
    dataIsStale: "数据已过期",
    collectorLooksBroken: "采集器似乎有问题",
    freshnessBanner: "{label}。上次采集器更新时间：{time}。",
    freshnessThresholds: "5 / 15 / 60 分钟阈值",
    clusterUtilization: "集群利用率",
    usedOfTotalSlots: "已用 {used} / 总计 {total} 个 slot",
    runningJobs: "运行中的作业",
    liveSchedulerCount: "调度器实时计数",
    queuedJobs: "排队作业",
    waitingInSchedulerQueue: "正在调度队列中等待",
    failedJobs: "失败作业",
    schedulerErrorInterpretation: "显式调度器错误/失败解释",
    jobsOnHold: "挂起作业",
    holdStatesOnly: "仅 hold 状态",
    myActiveJobs: "我的活跃作业",
    previewFromCurrentJobs: "来自当前作业的预览",
    health: "健康状况",
    clusterHealthSummary: "集群健康摘要",
    offlineNodes: "离线节点",
    freeSlots: "空闲 slot",
    healthRule: "健康规则",
    healthRuleText: "Healthy：调度器可访问。Degraded：部分节点离线。Down：调度器查询失败。",
    capacity: "容量",
    utilizationInUse: "当前有 {percent}% 的集群 slot 正在使用。",
    myJobs: "我的作业",
    activeJobsPreview: "活跃作业预览",
    openMyJobs: "打开我的作业",
    jobId: "作业 ID",
    name: "名称",
    state: "状态",
    submittedAt: "提交时间",
    startedAt: "开始时间",
    finishedAt: "完成时间",
    noActiveJobsRightNow: "你当前没有活跃作业。",
    loadingJobs: "正在加载作业…",
    failedJobsPage: "无法加载作业。",
    myJobsTitle: "我的作业",
    activeJobsAndHistory: "活跃作业和个人历史",
    jobsPageLede: "实时作业和 1 年历史分开显示。筛选项保持简单：搜索、状态、时间范围、分页。",
    activeJobs: "活跃作业",
    currentSchedulerView: "当前调度器视图",
    activeJobsCount: "{count} 个活跃作业",
    noActiveJobsOnCluster: "集群中没有活跃作业。",
    pastJobs: "历史作业",
    personalJobHistory: "1 年个人作业历史",
    search: "搜索",
    searchPlaceholder: "作业 ID 或名称",
    datePreset: "时间范围",
    noJobsMatched: "没有作业匹配所选筛选条件。",
    showingJobs: "显示 {total} 个作业中的 {shown} 个",
    previous: "上一页",
    page: "第",
    next: "下一页",
    loadingHistory: "正在加载历史…",
    failedHistory: "无法加载历史。",
    myHistory: "我的历史",
    personalHistoricalTrends: "个人历史趋势",
    historyPageLede: "短时间范围使用按小时汇总。较长时间范围切换为按天汇总，以保持页面可读。",
    range: "范围",
    submitted: "已提交",
    started: "已开始",
    finished: "已完成",
    failed: "失败",
    acrossPreset: "在 {preset} 内",
    jobsEnteringExecution: "进入执行的作业",
    completedSuccessfully: "成功完成",
    explicitFailuresOnly: "仅显式失败",
    trendChart: "趋势图",
    finishedVsFailedJobs: "完成作业与失败作业",
    preset: "预设",
    barChartLabel: "{preset} 的完成作业与失败作业柱状图",
    pageNotFound: "页面未找到",
    pageNotFoundLede: "使用主导航返回仪表板、作业或历史页面。",
    backToDashboard: "返回仪表板",
    healthy: "healthy",
    degraded: "degraded",
    down: "down",
    queued: "排队",
    running: "运行中",
    hold: "挂起",
    suspended: "暂停",
    error: "错误",
    finishedState: "已完成",
    deleted: "已删除",
    all: "全部",
  },
} satisfies Record<Language, Record<TranslationKey, string>>;

const statusKeys = {
  healthy: "healthy",
  degraded: "degraded",
  down: "down",
  queued: "queued",
  running: "running",
  hold: "hold",
  suspended: "suspended",
  error: "error",
  finished: "finishedState",
  deleted: "deleted",
  all: "all",
} as const satisfies Record<string, TranslationKey>;

const freshnessKeys = {
  fresh: "liveFeedHealthy",
  warn: "updateDelayed",
  stale: "dataIsStale",
  broken: "collectorLooksBroken",
} as const satisfies Record<FreshnessLevel, TranslationKey>;

export const languageOptions = [
  { value: "en", label: "English" },
  { value: "de", label: "Deutsch" },
  { value: "hu", label: "Magyar" },
  { value: "zh", label: "中文" },
] as const;

function fill(template: string, values?: Record<string, string | number>) {
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? `{${key}}`));
}

function readStored<T extends string>(key: string, fallback: T) {
  if (typeof window === "undefined") return fallback;
  const value = window.localStorage.getItem(key);
  return value ? value as T : fallback;
}

interface UiContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  theme: Theme;
  toggleTheme: () => void;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
  statusLabel: (value: string) => string;
  freshnessLabel: (level: FreshnessLevel) => string;
}

const UiContext = createContext<UiContextValue | null>(null);

export function UiProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => readStored("language", "en"));
  const [theme, setTheme] = useState<Theme>(() => readStored("theme", "light"));

  useEffect(() => {
    window.localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    window.localStorage.setItem("theme", theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const value = useMemo<UiContextValue>(() => {
    const table = translations[language];
    return {
      language,
      setLanguage,
      theme,
      toggleTheme: () => setTheme((value) => value === "dark" ? "light" : "dark"),
      t: (key, values) => fill(table[key], values),
      statusLabel: (value) => {
        const key = statusKeys[value as keyof typeof statusKeys];
        return key ? table[key] : value;
      },
      freshnessLabel: (level) => table[freshnessKeys[level]],
    };
  }, [language, theme]);

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
}

export function useUi() {
  const value = useContext(UiContext);
  if (!value) throw new Error("UiProvider missing");
  return value;
}
